spring:
  application:
    name: server
  datasource:
    url: jdbc:h2:mem:images
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update